<?php require 'templates/layout/header.phtml' ?>

<?php require 'templates/form_alta_tarea.phtml' ?>

<ul class="list-group">
<?php foreach($marcas as $marca): ?>
    <li class="list-group-item item-marca <?php if($marca->finalizada): ?> finished <?php endif ?>">
        <div class="label">
            <b><?= htmlspecialchars($marca->name) ?></b> | <?=($marca->id)?> | (Descripcion <?= $marca->descripcion ?>)
        </div>
        <div class="actions">
            <?php if(!$marca->finalizada): ?> 
                <a href="finalizar/<?= $marca->id ?>" type="button" class='btn btn-success btn-sm ml-auto'>Finalizar</a> 
            <?php endif ?>
            <a href="eliminar/<?= $marca->id ?>" type="button" class='btn btn-danger btn-sm ml-auto'>Borrar</a>
        </div>
    </li>
<?php endforeach ?>
</ul>

<p class="mt-3"><small>Mostrando <?=$count?> marcas</small></p>


<?php require 'templates/layout/footer.phtml' ?>
